// 验证几何变换、增强 B*-tree、ASF 约束、contour packing 和 routing adapter 的核心行为。
#include "test_support.hpp"

#include <filesystem>
#include <random>
#include <vector>

#include "sapr/geometry.hpp"
#include "sapr/io.hpp"
#include "sapr/optimizer.hpp"
#include "sapr/router.hpp"
#include "sapr/tree.hpp"

namespace {

// 判断两个矩形是否有面积重叠。
bool overlaps(const sapr::Rect& left, const sapr::Rect& right) {
    return left.x1 < right.x2 && left.x2 > right.x1 && left.y1 < right.y2 && left.y2 > right.y1;
}

// 从 placement 生成模块包围盒。
sapr::Rect placement_box(const sapr::Circuit& circuit, const sapr::Placement& placement) {
    const auto size = sapr::placed_size(circuit.modules.at(placement.module), placement);
    return {placement.x, placement.y, placement.x + size.first, placement.y + size.second};
}

}  // namespace

// 验证关键几何、增强树、对称 packing、扰动和求解结果保持稳定语义。
void run_router_tests() {
    const auto circuit = sapr::load_circuit(std::filesystem::path(SAPR_SOURCE_DIR) / "input");
    const auto& module = circuit.modules.at("M1");
    const auto& pin = circuit.pins.at("M1.G");
    require(sapr::placed_pin(module, pin, {"M1", 0, 0, 0, "R0"}) == std::pair<double, double>{0.8, 1.5}, "R0 pin transform failed");
    require(sapr::placed_pin(module, pin, {"M1", 0, 0, 90, "R90"}) == std::pair<double, double>{1.5, 0.8}, "R90 pin transform failed");
    require(sapr::placed_pin(module, pin, {"M1", 0, 0, 180, "R180"}) == std::pair<double, double>{3.2, 1.5}, "R180 pin transform failed");
    require(sapr::placed_pin(module, pin, {"M1", 0, 0, 270, "R270"}) == std::pair<double, double>{1.5, 3.2}, "R270 pin transform failed");
    require(sapr::placed_pin(module, pin, {"M1", 0, 0, 0, "MY"}) == std::pair<double, double>{3.2, 1.5}, "MY pin transform failed");

    const auto chain = sapr::make_chain_tree(circuit);
    require(chain.root == std::optional<std::string>{"M1"}, "chain root should be M1");
    require(chain.nodes.at("M1").left == std::optional<std::string>{"M2"}, "chain left child should preserve order");
    require(chain.nodes.at("M1").right_space.id == "M1:right", "right space should be created");

    auto tree = sapr::make_enhanced_tree(circuit);
    require(sapr::is_valid_tree(tree), "enhanced tree should be valid");
    require(sapr::self_symmetry_on_rightmost_branch(tree), "self-symmetry module should stay on right-most branch");
    require(tree.nodes.contains("M1"), "symmetry representative should be in tree");
    require(!tree.nodes.contains("M2"), "symmetry mirror should be generated by ASF packing");
    require(!tree.symmetry_groups.empty(), "symmetry groups should be recorded");
    require(sapr::collect_space_nodes(tree).size() >= tree.representative_order.size() * 2, "space nodes should be collectable");

    sapr::SpaceNode space{"space",
                          "M1",
                          sapr::SpaceNodeKind::Right,
                          {{"p",
                            "space",
                            {{"N", "A", "p", 1.0, 4.0, std::nullopt}, {"N", "p", "B", 1.0, 4.0, std::nullopt}},
                            {}}},
                          0.0};
    require(approx(space.required_space(), 4.0), "space formula should match paper equation");
    space.allocated_space = 9.0;
    require(approx(space.required_space(), 9.0), "feedback allocation should override smaller formula result");

    const sapr::SolverConfig config{5.0, 40.0, 7, 20};
    const auto request = sapr::pack_enhanced_tree(circuit, tree, config);
    require(request.placements.contains("M1"), "representative placement should exist");
    require(request.placements.contains("M2"), "mirror placement should exist");
    require(request.placements.at("M2").orient == "MY", "vertical symmetry pair should mirror on Y axis");
    require(request.placements.at("M2").x > request.placements.at("M1").x, "mirror should be placed beside representative");
    require(request.placements.at("M5").module == "M5", "self-symmetry module should remain placeable");
    require(request.placed_pins.size() == circuit.pin_order.size(), "routing request should expose placed pins");
    require(!request.active_region_blockers.empty(), "routing request should expose blockers");
    require(!request.linking_points.empty(), "routing request should expose LCPs");
    for (const auto& point : request.linking_points) {
        require(point.segments.size() >= 2, "each LCP should connect at least two segments");
        require(!point.location_candidates.empty(), "each LCP should expose physical candidates");
    }

    std::vector<sapr::Rect> boxes;
    for (const auto& module_id : request.placement_order) boxes.push_back(placement_box(circuit, request.placements.at(module_id)));
    for (std::size_t i = 0; i < boxes.size(); ++i) {
        for (std::size_t j = i + 1; j < boxes.size(); ++j) require(!overlaps(boxes[i], boxes[j]), "contour packing should avoid overlap");
    }

    auto feedback_tree = tree;
    sapr::RoutingFeedback feedback;
    feedback.required_space_by_node["M1:right"] = 25.0;
    sapr::apply_routing_feedback(feedback_tree, feedback);
    const auto expanded = sapr::pack_enhanced_tree(circuit, feedback_tree, config);
    require(expanded.placements.at("M3").x > request.placements.at("M3").x, "routing feedback should affect next packing");

    auto perturbed = tree;
    std::mt19937 rng(3);
    for (int i = 0; i < 10; ++i) {
        sapr::perturb_placement_tree(perturbed, rng);
        require(sapr::is_valid_tree(perturbed), "perturbed tree should stay valid");
        require(sapr::self_symmetry_on_rightmost_branch(perturbed), "perturbation should preserve ASF self branch");
    }

    const auto solution = sapr::solve_placement_aware(circuit, config);
    for (const auto& route : solution.routes) {
        require(route.x1 != route.x2 || route.y1 != route.y2, "zero-length route should be filtered");
    }
    require(solution.placements.size() == circuit.modules.size(), "all modules should be placed");
    require(approx(sapr::default_width(circuit, "VDD"), 5.0), "constrained width should use midpoint");
    require(approx(sapr::default_width(circuit, "OUT"), 1.0), "unconstrained width should be one");

    const auto repeat = sapr::solve_placement_aware(circuit, config);
    require(solution.placement_order == repeat.placement_order, "fixed seed should preserve placement order");
    for (const auto& id : solution.placement_order) {
        require(approx(solution.placements.at(id).x, repeat.placements.at(id).x), "fixed seed should preserve x");
        require(approx(solution.placements.at(id).y, repeat.placements.at(id).y), "fixed seed should preserve y");
        require(solution.placements.at(id).orient == repeat.placements.at(id).orient, "fixed seed should preserve orient");
    }

    const auto metrics = sapr::measure(circuit, solution);
    require(metrics.area > 0.0, "placement-aware area should be positive");
    require(metrics.wirelength > 0.0, "placement-aware wirelength should be positive");
    require(approx(metrics.penalty, 0.0), "adapter penalty should remain zero");
}
