if(NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "OUTPUT_DIR is required")
endif()
if(NOT DEFINED PNG_NAME)
  message(FATAL_ERROR "PNG_NAME is required")
endif()
foreach(path IN ITEMS "${OUTPUT_DIR}/placement.txt" "${OUTPUT_DIR}/routing.txt" "${OUTPUT_DIR}/${PNG_NAME}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "missing expected output: ${path}")
  endif()
  file(SIZE "${path}" size)
  if(size EQUAL 0)
    message(FATAL_ERROR "empty expected output: ${path}")
  endif()
endforeach()
